services:
  postgres-db:
    image: postgres
    container_name: bibliothequeApi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliotheque_db