server:
  address: 0.0.0.0  # Écoute sur toutes les interfaces
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
