server:
  address: 0.0.0.0  # Écoute sur toutes les interfaces
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bibliotheque_db # L'adresse de votre conteneur PostgreSQL
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        